var games = {'Mario' : [{'ChallengeTitle' : 'beat the game without dying',
                         'ChallengeDescription' : 'dont die in the game',
                         'difficulty' : 'medium'},
                         {'ChallengeTitle' : 'beat the game without breathing',
                         'ChallengeDescription' : 'dont breathe',
                         'difficulty' : 'hard'}],
             'Fortnite' : [{'ChallengeTitle' : 'win without building',
                         'ChallengeDescription' : 'dont build',
                         'difficulty' : 'hard'}],
             'Call of Duty' : [{'ChallengeTitle' : 'Prone all DaY!!!',
                         'ChallengeDescription' : 'Get to round 30 of zombies on Moon while prone the entire time. You must go prone in the first 1 second, and if you get up you lose. Can be single player or multiplayer.',
                         'difficulty' : 'hard'},
                         {'ChallengeTitle' : 'One box best box',
                         'ChallengeDescription' : 'beat zombies on any level with only boxing once',
                         'difficulty' : 'medium'},
                         {'ChallengeTitle' : 'knife in the back',
                         'ChallengeDescription' : 'win free for all online with only the combat knife. No perks allowed',
                         'difficulty' : 'easy'}],
             'Super Smash Bros Ultimate' : [{'ChallengeTitle' : 'PLANTTTT',
                         'ChallengeDescription' : 'WIN A FOR GLORY MATCH AS A LITERAL POTTED PLANT',
                         'difficulty' : 'easy'},
                         {'ChallengeTitle' : 'No B',
                         'ChallengeDescription' : 'Beat World of Light without using any B moves',
                         'difficulty' : 'medium'}]
            }